# Generated by Django 5.0.2 on 2024-02-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('numerator_names', models.TextField()),
                ('numerator', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnits',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataValueSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255)),
                ('categoryOptionCombo', models.CharField(blank=True, max_length=255, null=True)),
                ('attributeOptionCombo', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField(null=True)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataelement')),
                ('orgunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgunits')),
            ],
        ),
    ]
