# Generated by Django 5.0.2 on 2024-02-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='datavalueset',
            name='period_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quartely', 'Quartely')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datavalueset',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.program'),
        ),
    ]
